# Generated by Django 6.1.1 on 2026-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='titel',
            field=models.CharField(max_length=120),
        ),
    ]
