# Generated by Django 6.1.1 on 2026-09-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='titel',
            new_name='title',
        ),
    ]
